name: CI/CD

on:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
      - uses: actions/checkout@v3

      - name: Login to Aliyun Docker
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.DOCKER_REGISTRY_SERVER_URL }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2.3.0
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKER_REGISTRY_SERVER_URL }}/xiaobe/counter_weapp:latest
            ${{ secrets.DOCKER_REGISTRY_SERVER_URL }}/xiaobe/counter_weapp:${{ github.sha }}
          registry: ${{ secrets.DOCKER_REGISTRY_SERVER_URL }}